### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by GeorgeCiesinski** [GeorgeCiesinski/text-script#11]
Create standard unit tests in preparation for new contributors.

**Comment by scottwedge** [comment]
I'm teaching myself unit testing with the unittest module and would like to volunteer for this task.

**Comment by GeorgeCiesinski** [comment]
Hey Scott, thanks for volunteering! This is my first serious open source project where I'm opening up to contributions, so I'm a bit new to this. I am absolutely interested in the help, but since I planned to open this project to contributions at version 2 originally, I just need a bit of time to prepare - mostly just updating the documentation so that contributions are made within certain standards and cleaning up the code a bit before unit testing. Let me get back to you in a few days once I take care of this, and if you are still interested at the time then I would love the help!

Sorry about the help wanted label going up early. I wasn't aware that this flagged my project to the public!

**Comment by GeorgeCiesinski** [comment]
Closing this issue as specific test issues were opened. This issue is no longer required.
